
-- updating the descriptions of the athenas-coins

-- items
UPDATE `item_template` SET `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 10 Athenas Coins).' WHERE `entry` = '100601'; 
UPDATE `item_template` SET `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 20 Athenas Coins).' WHERE `entry` = '100602'; 
UPDATE `item_template` SET `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 50 Athenas Coins).' WHERE `entry` = '100603'; 
UPDATE `item_template` SET `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 100 Athenas Coins).' WHERE `entry` = '100604'; 

-- translations
UPDATE `locales_item` SET `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 10 Athenas Coins)', `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 10 Athenas Coins)' WHERE `entry` = '100601'; 
UPDATE `locales_item` SET `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 20 Athenas Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 20 Athenas Coins)' WHERE `entry` = '100602'; 
UPDATE `locales_item` SET `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 50 Athenas Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 50 Athenas Coins)' WHERE `entry` = '100603'; 
UPDATE `locales_item` SET `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 100 Athenas Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 100 Athenas Coins)' WHERE `entry` = '100604'; 
